server:
  port: 8088
  tomcat:
    max-connections: 20000
    max-threads: 1000
    min-spare-threads: 20
    connection-timeout: 3000
spring:
  application:
    name: amm-server
  resources:
    static-locations: classpath:/resources,classpath:/static
  datasource:
    mam:
      jdbc-url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: yang0106052509
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    amm:
      jdbc-url: jdbc:mysql://10.64.9.34:13306/application-maintenance-manage?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: Hljltchanhu@#23
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    gvm:
      jdbc-url: jdbc:mysql://10.64.9.34:13306/gardens-virescence-manage?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: Hljltchanhu@#23
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    sam:
      jdbc-url: jdbc:mysql://10.64.9.34:13306/sanitation-administration-manage?useUnicode=true&autoReconnect=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true
      username: root
      password: Hljltchanhu@#23
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
  jpa:
    database-platform: org.hibernate.spatial.dialect.mysql.MySQL8SpatialDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
      properties:
        hibernate:
          format_sql: true                  # 格式化SQL
          use_sql_comments: false           # 显示JPQL语句
          generate_statistics: false        # 显示SQL性能分析日志
  redis:
    database: 4
    host: 10.64.9.33
    port: 6379
    password: Hljltchanhu@#23
    timeout: 3000                         # 连接超时时间 毫秒
logging:
  level:
    com.amm.dao: debug
